img_compressor:
  # TIPO DE COMPRESION DE IMAGEN: JPEG2000, DEBT, SPIHT
  type: JPEG2000
  grayscale: True
  ratio: 500
  width: 960
  height: 720
  # width: 1920
  # height: 1440
  #width: 120
  #height: 90
