img_compressor:
  # TIPO DE COMPRESION DE IMAGEN: JPEG2000, DEBT, SPIHT
  type: DEBT
  # GUARDAR HISTORICO DE IMAGENES
  historic: True
  # ESCALA DE GRISES
  grayscale: True
  # RATIO DE COMPRESION PARA JPEG2000
  ratio: 500
  # REESCALADO PARA JPEG2000
  width: 0
  height: 0
  # width: 1920
  # height: 1440